# -*- coding: utf-8 -*-


__all__ = [
    "activity_task",
    "kfrank",
    "bgevent",
    "training",
    "bombnianevent",
    "shenhuo",
    "yuandanqifu",
    "arrestevent",
    "giftevent",
    "paradeevent",
    "borrowingarrowsevent",
    "ringevent",
    "kfwd",
    "duanwuevent",
    "towerstage",
    "kfevent",
    "qingmingevent",
    "dumpevent",
    "moongeneralevent",
    "superfanpai",
    "doubleelevenevent",
    "gemcard",
    "snowtrading",
    "kfzb",
    "goldgifttype",
    "kfpvp",
    "eatmooncaketevent",
    "springfestivalwishevent",
    "memoryevent",
    "boatevent",
]
